apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-cloud-run-service
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/fingerjoint-cr/finger_joint_deployment:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "1"
